-- ============================================================================
-- Construction Agent: kits + pgvector match_kits RPC
-- ----------------------------------------------------------------------------
-- Apply this migration manually in your external Supabase project:
--   1. supabase migration new construction_agent_kits
--   2. Paste this SQL into the new file
--   3. supabase db push
-- ----------------------------------------------------------------------------

-- 1. Enable pgvector (idempotent — Supabase ships the extension preinstalled).
create extension if not exists vector;

-- 2. Kits table — one row per construction "kit" the agent can recommend.
--    `embedding` is the OpenAI text-embedding-3-small vector (1536 dims) of
--    the kit's name + trade + keywords. Generated by a one-shot seed script
--    (see scripts/seed_kit_embeddings.ts notes at the bottom of this file).
create table if not exists public.kits (
  id          uuid primary key default gen_random_uuid(),
  slug        text unique not null,
  name        text not null,
  trade       text not null,
  description text not null,
  keywords    text[] not null default '{}',
  embedding   vector(1536),
  created_at  timestamptz not null default now()
);

-- 3. Kit items — products in each kit, with optional per-m² scaling.
create table if not exists public.kit_items (
  id            uuid primary key default gen_random_uuid(),
  kit_id        uuid not null references public.kits(id) on delete cascade,
  product_id    text not null,           -- matches src/data/catalog.ts PRODUCTS.id
  product_name  text not null,           -- denormalised for the agent's response
  unit          text not null,           -- "box / 200", "sheet", etc.
  per_m2        numeric,                 -- multiply by area to get qty
  base_qty      numeric not null default 0,
  display_order int not null default 0
);

create index if not exists kit_items_kit_id_idx on public.kit_items(kit_id);

-- 4. IVFFlat index for fast cosine similarity on the kit embedding.
--    `lists = 10` is fine for ≤ a few hundred kits; bump for larger sets.
create index if not exists kits_embedding_cosine_idx
  on public.kits using ivfflat (embedding vector_cosine_ops) with (lists = 10);

-- 5. RLS: kits are public read, no client writes (the seed script uses the
--    service role key to bypass RLS).
alter table public.kits enable row level security;
alter table public.kit_items enable row level security;

drop policy if exists "kits read public" on public.kits;
create policy "kits read public" on public.kits for select using (true);

drop policy if exists "kit_items read public" on public.kit_items;
create policy "kit_items read public" on public.kit_items for select using (true);

-- 6. RPC the construction-agent edge function calls. Returns the top N
--    matching kits ordered by cosine distance (lower = better), together
--    with their items. Embedding comparison is done server-side; the
--    edge function only ever sends the query embedding.
create or replace function public.match_kits(
  query_embedding vector(1536),
  match_count int default 1
)
returns table (
  kit_id        uuid,
  slug          text,
  name          text,
  trade         text,
  description   text,
  keywords      text[],
  similarity    float,
  items         jsonb
)
language sql
stable
as $$
  with ranked as (
    select
      k.id,
      k.slug,
      k.name,
      k.trade,
      k.description,
      k.keywords,
      1 - (k.embedding <=> query_embedding) as similarity
    from public.kits k
    where k.embedding is not null
    order by k.embedding <=> query_embedding
    limit match_count
  )
  select
    r.id as kit_id,
    r.slug,
    r.name,
    r.trade,
    r.description,
    r.keywords,
    r.similarity,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'product_id',   ki.product_id,
            'product_name', ki.product_name,
            'unit',         ki.unit,
            'per_m2',       ki.per_m2,
            'base_qty',     ki.base_qty
          )
          order by ki.display_order
        )
        from public.kit_items ki
        where ki.kit_id = r.id
      ),
      '[]'::jsonb
    ) as items
  from ranked r;
$$;

-- 7. Seed the 6 trade kits (without embeddings — those are added by the
--    one-shot script run after deploy). All product_ids match catalog.ts.
insert into public.kits (slug, name, trade, description, keywords)
values
  ('drywall-wall',   'Drywall Wall Kit',         'Drywall',    'Materials for finishing interior drywall partitions', array['drywall','trockenbau','gypsum','wand','rigips','gipskarton']),
  ('concrete-pour',  'Concrete Pour Kit',        'Concrete',   'Rapid-set concrete + tie wire for slabs and footings', array['concrete','rohbau','beton','slab','pour','estrich']),
  ('electrical-rough','Electrical Rough-in Kit', 'Electrical', 'Cable, connectors and tape for first-fix wiring',     array['electrical','elektro','wiring','cable','kabel','strom']),
  ('plumbing-rough', 'Plumbing Rough-in Kit',    'Plumbing',   'PEX and sealing tape for water rough-in',             array['plumbing','sanitär','pipe','rohr','wasser','pex']),
  ('roofing-membrane','Roofing Membrane Kit',    'Roofing',    'Membrane and nails for pitched roofs',                array['roof','dach','membrane','shingle','ziegel']),
  ('general-site',   'General Site Kit',         'General',    'Winter PPE, sealing tape and screws for any site',    array['general','allgemein','site','winter','ppe'])
on conflict (slug) do nothing;

-- 8. Seed kit_items. Quantities mirror src/components/TaskHelperFAB.tsx.
with k as (select id, slug from public.kits)
insert into public.kit_items (kit_id, product_id, product_name, unit, per_m2, base_qty, display_order)
select k.id, t.product_id, t.product_name, t.unit, t.per_m2, t.base_qty, t.ord
from k
join (values
  ('drywall-wall',    'gyp-2', 'Gypsum Board 12.5mm 1200×2500',     'sheet',       0.34, 0, 1),
  ('drywall-wall',    'gyp-1', 'Drywall Screws 3.5×35mm Phosphate', 'box / 500',   0.04, 0, 2),
  ('drywall-wall',    'gyp-4', 'Joint Compound 20kg',               'bucket',      0.15, 0, 3),
  ('drywall-wall',    'gyp-5', 'Joint Tape Paper 50mm',             'roll 75m',    0.05, 0, 4),
  ('drywall-wall',    'gyp-7', 'CD Ceiling Profile 60×27',          'bar 3m',      0.5,  0, 5),
  ('drywall-wall',    'gyp-8', 'Direct Hanger ES60',                'pcs',         2,    0, 6),
  ('drywall-wall',    'gyp-3', 'Drywall Knife 250mm Stainless',     'pcs',         null, 1, 7),
  ('concrete-pour',   'cn-1',  'Rapid Set Concrete 25kg',           'bag',         4,    0, 1),
  ('concrete-pour',   'cn-2',  'Rebar Tie Wire 1.4mm',              'roll',        0.1,  0, 2),
  ('electrical-rough','el-1',  'Cable NYM-J 3×1.5mm²',              'roll 100m',   0.05, 0, 1),
  ('electrical-rough','el-2',  'Wago 221 Connector 3-way',          'pack / 50',   0.04, 0, 2),
  ('electrical-rough','el-3',  'Insulation Tape Black 19mm',        'roll',        0.1,  0, 3),
  ('plumbing-rough',  'pl-1',  'PEX Pipe 16mm',                     'roll 50m',    0.04, 0, 1),
  ('plumbing-rough',  'pl-2',  'PTFE Sealing Tape 12mm',            'roll',        0.2,  0, 2),
  ('roofing-membrane','rf-2',  'Underlay Membrane 1.5×50m',         'roll',        0.015,0, 1),
  ('roofing-membrane','rf-1',  'Roofing Nails 2.8×25mm Galv.',      'kg',          0.05, 0, 2),
  ('general-site',    'glv-1', 'Winter Work Gloves — Thermal',      'pair',        null, 4, 1),
  ('general-site',    'tape-1','Window Sealing Tape 75mm — Standard','roll 25m',   null, 2, 2),
  ('general-site',    'scr-w-out-1','Wood Screws 5×60mm — Outdoor A2','box / 200', null, 1, 3)
) as t(slug, product_id, product_name, unit, per_m2, base_qty, ord)
on (k.slug = t.slug)
on conflict do nothing;

-- ============================================================================
-- Post-deploy step (one-shot, run from your laptop):
--
-- For each kit, generate an embedding from "<name>. <trade>. <keywords>" using
-- OpenAI text-embedding-3-small, then UPDATE public.kits SET embedding = ...
-- WHERE slug = '<slug>'. The construction-agent edge function expects every
-- kit row to have a non-null embedding.
-- ============================================================================
